-- 코드를 입력하세요
SELECT C.AUTHOR_ID, D.AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM (SELECT A.BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, SALES 
     FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
     WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1) C NATURAL JOIN AUTHOR D
GROUP BY C.AUTHOR_ID, CATEGORY
ORDER BY C.AUTHOR_ID, CATEGORY DESC