SELECT ID, FISH_NAME, FISH_INFO.LENGTH
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO 
WHERE FISH_INFO.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS FI
    WHERE FI.FISH_TYPE = FISH_INFO.FISH_TYPE
)
ORDER BY ID;